settings:

    # Windows: the drive where Steam keeps the game. If it's not C, uncomment this and change it
    #steam_drive: "C"

    # All platforms: the directory where Steam keeps the game. The default depends on your platform:
    #   Linux: $HOME/.local/share
    #   Mac OS: $HOME/Library/Application Support
    #   Windows XP: C:\Program Files
    #   Windows 7+: C:\Program Files (x86)
    # For other platforms, or if it's non-standard, you'll need to specify it
    # here. If you're on Windows, leave out the drive letter.
    steam_dir: "/" # absolute

    # The subdirectory of steam_dir where Steam keeps its apps. You shouldn't need to change this.
    # (For Windows, slashes are automatically changed to backslashes, so this default works.)
    steam_apps: "Games"

    # Which game we're looking at. This is the name of the directory under
    # steam_dir where the game is kept.
    game: "Hearts of Iron IV"

    # Language to extract in. Note that although the program can extract
    # non-English localization strings from the game, only English messages
    # are produced otherwise.
    language: "english"

    # Game version (major patch number). Only used to add version templates.
    version: "1.9.1"

    # Mod name the name of the folder of the mod you're trying to parse
    #mod_name:

    # All Platforms where mod files are kept
    #   Windows: C:\Users\<Username>\Documents\Paradox Interactive\Hearts of Iron IV\mod
    #   Mac OS: ~/Documents/Paradox Interactive/Hearts of Iron IV/mod
    #   Linux: ~/.local/share/Paradox Interactive/Hearts of Iron IV/mod
    #
    #mod_path:
